# fly.toml app configuration file generated for pbs-server on 2026-03-04T20:21:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pbs-server'
primary_region = 'ord'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
