/**
 * Auto-generated trainer sprite map — DO NOT EDIT MANUALLY.
 */
import { ImageSourcePropType } from 'react-native';

const TRAINER_SPRITE_MAP: Record<string, ImageSourcePropType> = {
  'acetrainer-gen4': require('../../assets/sprites/trainers/acetrainer-gen4.png'),
  'beauty-gen4': require('../../assets/sprites/trainers/beauty-gen4.png'),
  'blackbelt-gen4': require('../../assets/sprites/trainers/blackbelt-gen4.png'),
  'blue': require('../../assets/sprites/trainers/blue.png'),
  'brendan': require('../../assets/sprites/trainers/brendan.png'),
  'bugcatcher': require('../../assets/sprites/trainers/bugcatcher.png'),
  'burglar': require('../../assets/sprites/trainers/burglar.png'),
  'calem': require('../../assets/sprites/trainers/calem.png'),
  'channeler': require('../../assets/sprites/trainers/channeler.png'),
  'cooltrainer': require('../../assets/sprites/trainers/cooltrainer.png'),
  'cynthia': require('../../assets/sprites/trainers/cynthia.png'),
  'dawn': require('../../assets/sprites/trainers/dawn.png'),
  'elio': require('../../assets/sprites/trainers/elio.png'),
  'ethan': require('../../assets/sprites/trainers/ethan.png'),
  'fisherman': require('../../assets/sprites/trainers/fisherman.png'),
  'gentleman': require('../../assets/sprites/trainers/gentleman.png'),
  'gloria': require('../../assets/sprites/trainers/gloria.png'),
  'guitarist': require('../../assets/sprites/trainers/guitarist.png'),
  'hiker': require('../../assets/sprites/trainers/hiker.png'),
  'hilbert': require('../../assets/sprites/trainers/hilbert.png'),
  'hilda': require('../../assets/sprites/trainers/hilda.png'),
  'iris': require('../../assets/sprites/trainers/iris.png'),
  'juggler': require('../../assets/sprites/trainers/juggler.png'),
  'lance': require('../../assets/sprites/trainers/lance.png'),
  'lass': require('../../assets/sprites/trainers/lass.png'),
  'leaf': require('../../assets/sprites/trainers/leaf.png'),
  'lucas': require('../../assets/sprites/trainers/lucas.png'),
  'lyra': require('../../assets/sprites/trainers/lyra.png'),
  'may': require('../../assets/sprites/trainers/may.png'),
  'n': require('../../assets/sprites/trainers/n.png'),
  'nate': require('../../assets/sprites/trainers/nate.png'),
  'pokefan': require('../../assets/sprites/trainers/pokefan.png'),
  'pokemaniac': require('../../assets/sprites/trainers/pokemaniac.png'),
  'psychic': require('../../assets/sprites/trainers/psychic.png'),
  'ranger': require('../../assets/sprites/trainers/ranger.png'),
  'red': require('../../assets/sprites/trainers/red.png'),
  'rocker': require('../../assets/sprites/trainers/rocker.png'),
  'rosa': require('../../assets/sprites/trainers/rosa.png'),
  'roughneck': require('../../assets/sprites/trainers/roughneck.png'),
  'sailor': require('../../assets/sprites/trainers/sailor.png'),
  'scientist': require('../../assets/sprites/trainers/scientist.png'),
  'selene': require('../../assets/sprites/trainers/selene.png'),
  'serena': require('../../assets/sprites/trainers/serena.png'),
  'steven': require('../../assets/sprites/trainers/steven.png'),
  'swimmer': require('../../assets/sprites/trainers/swimmer.png'),
  'victor': require('../../assets/sprites/trainers/victor.png'),
  'worker': require('../../assets/sprites/trainers/worker.png'),
  'youngster': require('../../assets/sprites/trainers/youngster.png'),
};

export default TRAINER_SPRITE_MAP;
